name: ClientWorker 
catch_rules:
  - rule: _
    transform_rules:
      # - search: \#.+
      #   searchin: url
      #   replace: ''
      # - search: _ 
      #   action: fetch
      #   fetch:
      #     engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503
      - search: ^https:\/\/cdn1\.tianli0\.top\/npm\/
        replace: 
          - https://npm.elemecdn.com/
          - _
      - search: ([^\/.]+)\/$
        replace: $1/index.html
      # - search: ^https:\/\/(.*?)yisous.xyz\/
      #   replace:
      #     - https://ariasakablog.s3.ladydaily.com/
      #     - _ 
      # - search: ^http:\/\/localhost:4000\/
      #   replace:
      #     - https://ariasakablog.s3.ladydaily.com/
      #     - _ 